config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :records
  end

  resources :records
  root 'records#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  serialize :tracks, Array
end

app/controllers/api/records_controller.rb
class Api::RecordsController < ApplicationController
  before_action :set_default_format

  def index
    @records = Record.all
  end

  def show
    @record= Record.find(params[:id])
  end

  private

  def set_default_format
    request.format = :json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    if params[:genre]
      @records = Record.where("series LIKE ?", "%#{params[:genre]}%").paginate(:page => params[:page])
    elsif params[:author]
      @records = Record.where("author LIKE ?", "%#{params[:author]}%").paginate(:page => params[:page])
    else
      @records = Record.order(sort_column + " " + sort_direction).paginate(:page => params[:page])
    end
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      puts 'saved'
    else
      puts 'not saved'
    end
  end

  def show
    @record= Record.find(params[:id])
  end

  private

  def record_params
    params.require(:record).permit(:drc_id, :collection, :author, :location, :year, :date, :date_digitized, :date_issued, :description_html, :description_notes, :recording_format, :length, :drc_link, :language, :institution_repo, :institution_digital, :is_part_of, :series, :rights_uri, :rights, :subject, :subject_two, :subject_three, :title_alternitive, :title_text, :recording_type, :tracks)
  end

  def sort_column
    params[:sort] || "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/drc_ids_helper.rb
module DrcIdsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EllistonApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/records/_genre.html.erb
<div>
  <h1>Genre Hits</h1>
  <% @records.each do |listing| %>
    <li> <%= listing.drc_id %> </li>
  <% end %>
</div>

app/views/records/index.html.erb
<div class="row navbar">
  <div class="one-half column">
    <h2><%= link_to "Elliston", root_path %></h2>
      <%= link_to "All", :controller => "records", :genre => "" %>  |  
      <%= link_to "Poetry", :controller => "records", :genre => "poetry" %>  |  
      <%= link_to "Fiction", :controller => "records", :genre => "fiction" %>  |  
      <%= link_to "Lectures", :controller => "records", :genre => "lecture" %>
    </div>
  <div class="one-half column">
    <%= form_tag records_path, :method => "get" do %>
      <h3>Search</h3>
        <%= text_field_tag :author, params[:author] %>
        <%= submit_tag "Search", :name => nil %>
    <% end %>
  </div>
</div>

<% if @records.present? %>
  <table>
    <tr>
      <th><%= sortable "author" %></th>
      <th><%= sortable "year" %></th>
      <th><%= sortable "drc_id", "Id" %></th>
      <th>Info</th>
    </tr>
    <% @records.each_with_index do |record, index| %>
      <tr>
        <td><%= link_to record.author.truncate(25, omission: '...'), record, :class => "button", :style => "width: 100%;" %></td>
        <td><%= record.year %></td>
        <td><b><%= record.drc_id %></b></td>
        <td>
          <ul>
            <li><%= record.date %></li>
            <li><%= record.series %></li>
            <li>No. of tracks: <%= record.tracks.length %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h5>Sorry, no records available.</h5>
<% end %>

<%= will_paginate @records %>

app/views/records/show.html.erb
<h2><%= @record.author %></h2>
<h5>DRCID: <%= @record.drc_id %></h5>
<h5>Date: <%= @record.date_issued %></h5>

<% @record.tracks.each_with_index do |track, index| %>
  <% if index == 0 %>
    <audio id="audio" preload="auto" tabindex="0" controls="" >
      <source src="<%= track[:mp3] %>">
      Sorry, audio not supported.
    </audio>
    <ul id="playlist">
        <li class="active">
  <% end %>
  <% unless index == 0 %>
    <li>
  <% end %>
    <a href="<%= track[:mp3] %>">
      <% unless index == 0 %>
        <%= track[:track_num] %> -
      <% end %>
        <%= track[:title] %>
    </a>
  </li>
<% end %>
</ul>